In [1]:
from pathlib import Path

import numpy as np

In [4]:
input_text = Path("input.txt").read_text()
input_text.split()[:10]

['011110011110',
 '101101001111',
 '000000010101',
 '100111001010',
 '110000011010',
 '011101010101',
 '011110001100',
 '010111111001',
 '111011100101',
 '011110000110']

In [5]:
input_nested_list = [[int(i) for i in row] for row in input_text.split()]

In [10]:
input_arr = np.array(input_nested_list)

input_arr.shape

(1000, 12)

In [14]:
gamma_arr = np.array(np.sum(input_arr, axis=0) > 500, dtype=int)
gamma_arr

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1])

In [26]:
def bin_arr_2_int(bin_arr):
    """
    convert array of 1s and 0s to integer equivalent of binary representation
    """
    
    return int("".join([str(i) for i in bin_arr]), 2)

In [27]:
gamma = bin_arr_2_int(gamma_arr)
gamma

199

In [28]:
eps_arr = np.array(np.sum(input_arr, axis=0) <= 500, dtype=int)

eps = bin_arr_2_int(eps_arr)

eps

3896

In [21]:
gamma*eps

775304

# Part 2

In [24]:
oxy_arr = input_arr

for i in range(oxy_arr.shape[1]):
    
    print(f"Step {i}")
    
    print("Oxy shape", oxy_arr.shape)
    print("Oxy head", oxy_arr[:10, :])
    
    most_common_bit_value = int(sum(oxy_arr[:,i]) >= oxy_arr.shape[0]/2)
    
    print("Most Common Bit Value" , most_common_bit_value)
    
    oxy_arr = oxy_arr[ oxy_arr[:,i] == most_common_bit_value, :]

Step 0
Oxy shape (1000, 12)
Oxy head [[0 1 1 1 1 0 0 1 1 1 1 0]
 [1 0 1 1 0 1 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 1 1 0 0 1 0 1 0]
 [1 1 0 0 0 0 0 1 1 0 1 0]
 [0 1 1 1 0 1 0 1 0 1 0 1]
 [0 1 1 1 1 0 0 0 1 1 0 0]
 [0 1 0 1 1 1 1 1 1 0 0 1]
 [1 1 1 0 1 1 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0 0 1 1 0]]
Most Common Bit Value 0
Step 1
Oxy shape (506, 12)
Oxy head [[0 1 1 1 1 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 1 0 1 0 1]
 [0 1 1 1 0 1 0 1 0 1 0 1]
 [0 1 1 1 1 0 0 0 1 1 0 0]
 [0 1 0 1 1 1 1 1 1 0 0 1]
 [0 1 1 1 1 0 0 0 0 1 1 0]
 [0 1 0 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 1 0 0 0 1 0 0 1 0 1]
 [0 1 0 1 0 0 0 1 1 1 1 0]]
Most Common Bit Value 0
Step 2
Oxy shape (262, 12)
Oxy head [[0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 1 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 1 1 0 1 0 1 0 1]
 [0 0 0 1 1 1 0 1 0 0 1 1]
 [0 0 1 0 0 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 0 1 1 1 1 0]
 [0 0 1 1 1 1 1 0 1 1 0 1]
 [0 0 0 1 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 0 1 0 0]]
Most Common Bit Value 0
Step 3

In [35]:
oxy = bin_arr_2_int(oxy_arr.flat)
oxy

509

In [41]:
co2_arr = input_arr

for i in range(co2_arr.shape[1]):
    
    print(f"Step {i}")
    
    print("co2 shape", co2_arr.shape)
    print("co2 head\n", co2_arr[:10, :])
    
    if co2_arr.shape[0] == 1:
        break
    
    least_common_bit_value = int(sum(co2_arr[:,i]) < co2_arr.shape[0]/2)
    
    print("Least Common Bit Value" , least_common_bit_value)
    
    co2_arr = co2_arr[ co2_arr[:,i] == least_common_bit_value, :]
    
    

Step 0
co2 shape (1000, 12)
co2 head
 [[0 1 1 1 1 0 0 1 1 1 1 0]
 [1 0 1 1 0 1 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 1 1 0 0 1 0 1 0]
 [1 1 0 0 0 0 0 1 1 0 1 0]
 [0 1 1 1 0 1 0 1 0 1 0 1]
 [0 1 1 1 1 0 0 0 1 1 0 0]
 [0 1 0 1 1 1 1 1 1 0 0 1]
 [1 1 1 0 1 1 1 0 0 1 0 1]
 [0 1 1 1 1 0 0 0 0 1 1 0]]
Least Common Bit Value 1
Step 1
co2 shape (494, 12)
co2 head
 [[1 0 1 1 0 1 0 0 1 1 1 1]
 [1 0 0 1 1 1 0 0 1 0 1 0]
 [1 1 0 0 0 0 0 1 1 0 1 0]
 [1 1 1 0 1 1 1 0 0 1 0 1]
 [1 1 0 0 0 1 0 0 1 0 0 0]
 [1 1 0 1 0 1 0 0 1 1 1 1]
 [1 0 0 1 1 1 0 1 1 1 0 0]
 [1 1 1 0 0 1 0 0 0 1 1 1]
 [1 0 0 1 0 1 1 1 1 1 1 1]
 [1 1 0 0 1 0 1 0 1 1 0 0]]
Least Common Bit Value 0
Step 2
co2 shape (240, 12)
co2 head
 [[1 0 1 1 0 1 0 0 1 1 1 1]
 [1 0 0 1 1 1 0 0 1 0 1 0]
 [1 0 0 1 1 1 0 1 1 1 0 0]
 [1 0 0 1 0 1 1 1 1 1 1 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [1 0 0 1 1 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 0 0 1 0 1 1]
 [1 0 1 0 0 0 1 0 0 1 1 0]
 [1 0 0 0 0 1 0 0 0 1 1 1]
 [1 0 1 1 0 1 1 0 0 0 0 1]]
Least Common Bit Value 1


In [42]:
co2_arr

array([[1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1]])

In [43]:
co2 = bin_arr_2_int(co2_arr.flat)
co2

2693

In [44]:
co2*oxy

1370737